### ISSUE TITLE
Setting clipboard=unnamedplus doesn't work

### ISSUE THREAD

**Issue by svban** [inkarkat/vim-RepeatableYank#1]
Setting clipboard=unnamedplus doesn't work. 
Plugin does not work if we set set clipboard=unnamedplus. 
I am also using this setting             let g:RepeatableYank_DefaultRegister = "+"

**Comment by inkarkat** [comment]
Thanks for reporting this! Apparently, nobody has used the plugin in that configuration yet; supporting that wasn't difficult.

You also don't need to define `g:RepeatableYank_DefaultRegister` any longer, as it now defaults to the configured default register.

**Comment by svban** [comment]
Thank you so much for the quick fix. Works like a charm now!!
